### ISSUE TITLE
what is azure authentication flow?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#1]

**Comment by JQuarticx** [comment]
@FourTimes 


process flow

![image](https://user-images.githubusercontent.com/57703276/143731272-18d2402c-c40e-4eb3-a6b8-0dd7e8b50b4a.png)

**Comment by Joe-Joy** [comment]
@dodonotdo
### `What is Azure Resource Manager?`

> Azure Resource Manager is the deployment and management service for Azure. It provides a management layer that enables you to create, update, and delete resources in your Azure account. You use management features, like access control, locks, and tags, to secure and organize your resources after deployment.

### `Pocess Flow:-`
![image](https://user-images.githubusercontent.com/71425992/143734050-e69bc0c7-3ca6-4c22-95f1-14be0504272b.png)

**resource :-** 
- A manageable item that is available through Azure. Virtual machines, storage accounts, web apps, databases, and virtual networks are examples of resources. Resource groups, subscriptions, management groups, and tags are also examples of resources.

**resource group :-** 
 - A container that holds related resources for an Azure solution. The resource group includes those resources that you want to manage as a group. You decide which resources belong in a resource group based on what makes the most sense for your organization. See Resource groups.

**resource provider -** 
- A service that supplies Azure resources. For example, a common resource provider is Microsoft.Compute, which supplies the virtual machine resource. Microsoft.Storage is another common resource provider. See Resource providers and types.

**Resource Manager template -**
- A JavaScript Object Notation (JSON) file that defines one or more resources to deploy to a resource group, subscription, management group, or tenant. The template can be used to deploy the resources consistently and repeatedly. 

### `Four Level of scope:`

![image](https://user-images.githubusercontent.com/71425992/143733889-511e7d93-63a2-4000-b663-73e4cd52c961.png)

**Comment by Yuvi991** [comment]
**Flows of Authentication:**

**Login --->Send credentials to agent--->verification--->return success/failure--->Return response--->Authenticated finally**

  
```
-         Purpose is to identify and authentication the user.
-         Authentication is an input to other methods.
-         Particularly for associate Account and capture .
-         This means that the proof of authentication.
```


![Autentication flow](https://user-images.githubusercontent.com/95156779/143773973-282cac94-8ba7-48ee-947d-7d4da47bbb51.png)

**Comment by vijaybaskarnov1995** [comment]
<img width="571" alt="Authentication 1" src="https://user-images.githubusercontent.com/95157073/143904191-3059950a-022b-455d-a391-23a1b5806dd1.png">

**Comment by vijaybaskarnov1995** [comment]
![authentication 2](https://user-images.githubusercontent.com/95157073/143904403-9b50d271-0d50-43b5-b680-a46080b0da56.jpg)
