### ISSUE TITLE
what is azure?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#10]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### Azure:-

- At its core, Azure is a public cloud computing platform—with solutions including Infrastructure as a Service (**IaaS**), Platform as a Service (**PaaS**), and Software as a Service (**SaaS**) that can be used for services such as analytics, virtual computing, storage, networking, and much more.

![image](https://user-images.githubusercontent.com/71425992/144183291-1d6d61c8-f61f-42c1-84e6-ece7356e904d.png)
