### ISSUE TITLE
what are providers?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#11]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### Providers:-
- When deploying resources, you frequently need to retrieve information about the resource providers and types. For example, if you want to store keys and secrets, you work with the Microsoft.KeyVault resource provider. This resource provider offers a resource type called vaults for creating the key vault.

The name of a resource type is in the format: **{resource-provider}/{resource-type}**. The resource type for a key vault is Microsoft.KeyVault/vaults.

1. View all resource providers in Azure.
2. Check registration status of a resource provider.
3. Register a resource provider.
4. View resource types for a resource provider.
5. View valid locations for a resource type.
6. View valid API versions for a resource type
