### ISSUE TITLE
what is subscription?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#12]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### Subscription:-

- An Azure subscription is mandatory when you are using Azure resources.
- An Azure resource is a manageable item like a database, web application, virtual network, virtual machine (VM) or storage account that is available on Azure. 
- A subscription authenticates and authorizes you to use these resources.

**Comment by vijaybaskarnov1995** [comment]
An Azure subscription is linked to a single account, the one that was used to create the subscription and is used for billing purposes.

![image](https://user-images.githubusercontent.com/95157073/144275456-5db51411-0eb0-4563-83d4-3ef9ee447f27.png)
