### ISSUE TITLE
what is REST API?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#14]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### Rest APT:-

- A RESTful API or REST API is an architectural style for an application program interface (API) that uses HTTP requests to access and use data. 
- That data can be used to GET, PUT, POST and DELETE data types, which refers to the reading, updating, creating and deleting of operations concerning resources.

![image](https://user-images.githubusercontent.com/71425992/144177853-acf4ec27-80b3-4bab-bdcf-5959d3a0f82d.png)

**Comment by vijaybaskarnov1995** [comment]
An API, or application programming interface, is a set of rules that define how applications or devices can connect to and communicate with each other.

![image](https://user-images.githubusercontent.com/95157073/144268213-f653be6e-86ab-4b1a-bf90-3f120b8328bc.png)
