### ISSUE TITLE
what is an arm template?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#15]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### ARM Template:-
- Azure Resource Manager (ARM) is an Azure service you can use to manage and deploy resources using an infrastructure as code paradigm. 
- It enables you to provision, modify, and delete resources using a variety of features including access controls, tags, and locks.

![image](https://user-images.githubusercontent.com/71425992/144176264-99821e15-a92d-4abc-ace0-941957a9e389.png)

**Comment by vijaybaskarnov1995** [comment]
An Azure Resource Manager template consists of JSON and expressions that you can use to construct values for your deployment.
