### ISSUE TITLE
what is sdk and purpose of it?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#16]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### SDK:-
- A software development kit (SDK) is a set of software development tools that allows the creation of applications for a certain software package, software framework, hardware platform, computer system, video game console, operating system, or similar development platform.

**Comment by vijaybaskarnov1995** [comment]
SDK stands for software development kit or devkit for short. It’s a set of software tools and programs used by developers to create applications for specific platforms.

SDK tools will include a range of things, including libraries, documentation, code samples, processes, and guides that developers can use and integrate into their own apps. SDKs are designed to be used for specific platforms or programming languages.
