### ISSUE TITLE
network architecture

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#2]

**Comment by Joe-Joy** [comment]
### Network Architecture:-
- Network architecture is the design of a computer network.
- It is a framework for the specification of a network's physical components and their functional organization and configuration, its operational principles and procedures, as well as communication protocols used.

**Comment by vijaybaskarnov1995** [comment]
![image](https://user-images.githubusercontent.com/95157073/144272131-64dca900-5e16-408b-8632-a945fe0b0ee4.png)
