### ISSUE TITLE
diff between public and private IP addresses?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#3]

**Comment by Joe-Joy** [comment]
@dodonotdo
|PRIVATE IP ADDRESS|PUBLIC IP ADDRESS|
|--------------------|-------------------|
|Scope is local. | Scope is global.|
|It is used to communicate within the network. | It is used to communicate outside the network.|
|Private IP addresses of the systems connected in a network differ in a uniform manner. | Public IP may differ in uniform or non-niform manner.|
|It works only in LAN. | It is used to get internet service.|
|It is used to load network operating system. | It is controlled by ISP.|
|It is available in free of cost. | It is not free of cost.|
|Private IP can be known by entering “ipconfig” on command prompt. | Public IP can be known by searching “what is my ip” on google.|
|**Range:** Class A) 10.0.0.0 – 10.255.255.255, Class B) 172.16.0.0 – 172.31.255.255, Class C)192.168.0.0 – 192.168.255.255 | **Range:** Besides private IP addresses, rest are public.|

**Comment by vijaybaskarnov1995** [comment]
![image](https://user-images.githubusercontent.com/95157073/144271732-0dad9ce2-4d1e-4021-b8cf-14106d09292b.png)
