### ISSUE TITLE
types of ip address?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#4]

**Comment by Joe-Joy** [comment]
@dodonotdo
### Type of IP address:-       
```bash   
            1. Private IP address
            2. Public IP address
            3. Static IP address
            4. Dynamic IP address
```

**Comment by vijaybaskarnov1995** [comment]
**Consumer IP addresses**
Every individual or business with an internet service plan will have two types of IP addresses:

1.Private IP addresses
2.Public IP addresses

**Public IP addresses**
Public IP addresses come in two forms.

1.Dynamic IP addresses
2.Static IP addresses

**Website IP addresses**
For website owners who don’t host their own server, and instead rely on a web hosting package – which is the case for most websites – there are two types of website IP addresses. 

1.Shared IP addresses
2.Dedicated IP addresses
