### ISSUE TITLE
what is gateway?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#5]

**Comment by Yuvi991** [comment]
- Gateway is basically an interface that allows one network to communicate with another network .
- where the interface is nothing but the communication media between two things.
- Example: The touchpad is the interface between you and mobile or keyboard is the interface between you and laptop.
-  In the same way, the gateway is the interface between two networks

![Screenshot from 2021-11-30 01-58-59](https://user-images.githubusercontent.com/95156779/143938386-7eed6a11-ac2d-4c13-b40c-2723af9f2f50.png)

**Comment by Joe-Joy** [comment]
@dodonotdo
### Gateway:-


- Gateway is a network hardware device that is used for making communication in between two networks with different transmission protocol together, and it is an entry and exit “Gate” for the networks that helps to bypass the all data with the gateway prior to being routed.
- 
![image](https://user-images.githubusercontent.com/71425992/143998032-206571ce-3ec3-4f07-a609-be23ab158c63.png)

**Comment by vijaybaskarnov1995** [comment]
A gateway is a hardware device that goes about as a “gate” between two networks.

![image](https://user-images.githubusercontent.com/95157073/144276229-252a0ac5-2323-4f99-af66-6322787f43ab.png)
