### ISSUE TITLE
what is subnet?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#6]

**Comment by Yuvi991** [comment]
- A subnet, or subnetwork, is a network inside a network. 
- Subnets make networks more efficient. 
- Through subnetting, network traffic can travel a shorter distance without passing through unnecessary routers to reach its destination.
![Screenshot from 2021-11-30 01-54-08](https://user-images.githubusercontent.com/95156779/143937798-66ca1dea-1fa2-47d1-8816-950434e5ac59.png)

**Comment by Joe-Joy** [comment]
@dodonotdo
### Subnet:-
- A subnetwork or subnet is a logical subdivision of an IP network. 
- The practice of dividing a network into two or more networks is called subnetting. Computers that belong to the same subnet are addressed with an identical most-significant bit-group in their IP addresses.

![image](https://user-images.githubusercontent.com/71425992/143998808-d6bba95e-dc3c-4300-b2af-6b44278c993a.png)

**Comment by FourTimes** [comment]
> @dodonotdo
> 
> ### Subnet:-
> * A subnetwork or subnet is a logical subdivision of an IP network.
> * The practice of dividing a network into two or more networks is called subnetting. Computers that belong to the same subnet are addressed with an identical most-significant bit-group in their IP addresses.
> 
> ![image](https://user-images.githubusercontent.com/71425992/143998808-d6bba95e-dc3c-4300-b2af-6b44278c993a.png)

good
