### ISSUE TITLE
what is IP?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#7]

**Comment by Joe-Joy** [comment]
@dodonotdo
### IP address:-

- An IP address is a unique address that identifies a device on the internet or a local network. 
- IP stands for "Internet Protocol," which is the set of rules governing the format of data sent via the internet or local network.

- In essence, IP addresses are the identifier that allows information to be sent between devices on a network: they contain location information and make devices accessible for communication. 
- The internet needs a way to differentiate between different computers, routers, and websites. IP addresses provide a way of doing so and form an essential part of how the internet works.

**Comment by Yuvi991** [comment]
- The Internet Protocol Address (or IP Address) is a unique address that computing devices such as personal computers, tablets, and smartphones.
-  It use to identify themselves and communicate with other devices in the IP network.
-  Any device connected to the IP network must have a unique IP address within the network. 
- An IP address is analogous to a street address or telephone number in that it is used to uniquely identify an entity.
