### ISSUE TITLE
what is the cloud?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#9]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### Cloud:-
- "The cloud" refers to servers that are accessed over the Internet, and the software and databases that run on those servers. 

- Cloud servers are located in data centers all over the world. By using cloud computing, users and companies do not have to manage physical servers themselves or run software applications on their own machines.

![image](https://user-images.githubusercontent.com/71425992/144179167-78fa4ee5-f0c3-4805-a5c4-56b99ec6a7d6.png)
